// Original ZynAddSubFX author Nasca Octavian Paul
// Copyright (C) 2002-2005 Nasca Octavian Paul
// Copyright 2009-2010, Alan Calvert

// This file is part of yoshimi, which is free software: you can redistribute
// it and/or modify it under the terms of version 2 of the GNU General Public
// License as published by the Free Software Foundation.

// yoshimi is distributed in the hope that it will be useful, but WITHOUT ANY
// WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
// FOR A PARTICULAR PURPOSE.   See the GNU General Public License (version 2 or
// later) for more details.

// You should have received a copy of the GNU General Public License along with
// yoshimi; if not, write to the Free Software Foundation, Inc., 51 Franklin
// Street, Fifth Floor, Boston, MA  02110-1301, USA.

// This file is a derivative of the ZynAddSubFX original, modified January 2010

// generated by Fast Light User Interface Designer (fluid) version 1.0302

#ifndef MidiControllerUI_h
#define MidiControllerUI_h
#include <FL/Fl.H>
#include "WidgetPDialUI.h"
#include <FL/Fl_Button.H>
#include <FL/Fl_Spinner.H>
#include <FL/Fl_Input.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Scroll.H>
#include <stdio.h>
#include "Misc/MiscFuncs.h"
#include "Misc/SynthEngine.h"
class WidgetPDial;

class MidiCCRack : public Fl_Group {
  Fl_Group* embossedGroup;WidgetPDial* dial;Fl_Input* title;Fl_Spinner* spinner;midiControl* controller; 
public:
  MidiCCRack(int x, int y, int w, int h) ;
  void setMidiController(midiControl* contr);
private:
  static void startRecording(Fl_Widget* w, void* p);
  static void removeController(Fl_Widget* w, void* p);
  static void spinnerChanged(Fl_Widget* w, void* p);
  static void setMin(Fl_Widget* w, void* p);
  static void setMax(Fl_Widget* w, void* p);
public:
  SynthEngine *synth; 
};

class MidiCCWindow : public Fl_Double_Window {
public:
  MidiCCWindow(int x, int y, int w, int h, SynthEngine* _synth, const char *title=0);
  void Show();
  void updateRack();
private:
  Fl_Scroll *scrollArea; 
public:
  SynthEngine *synth; 
};
extern MidiCCWindow* midiccwindow;
#endif
