// generated by Fast Light User Interface Designer (fluid) version 1.0302

#include "Misc/ControllableByMIDIUI.h"
// ControllableByMIDIUI.cc
// Original ZynAddSubFX author Nasca Octavian Paul
// Copyright (C) 2002-2005 Nasca Octavian Paul
// Copyright 2009-2010, Alan Calvert

// This file is part of yoshimi, which is free software: you can redistribute
// it and/or modify it under the terms of the GNU Library General Public
// License as published by the Free Software Foundation; either version 2 of
// the License, or (at your option) any later version.

// yoshimi is distributed in the hope that it will be useful, but WITHOUT ANY
// WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
// FOR A PARTICULAR PURPOSE.   See the GNU General Public License (version 2 or
// later) for more details.

// You should have received a copy of the GNU General Public License along with
// yoshimi; if not, write to the Free Software Foundation, Inc., 51 Franklin
// Street, Fifth Floor, Boston, MA  02110-1301, USA.

// This file is a derivative of the ZynAddSubFX original, modified January 2010


void ControllableByMIDIUI::refresh() {
  ;
}

void ControllableByMIDIUI::reassignMidi(ControllableByMIDI *ctrl) {
	controller = ctrl; 

	controller->reassignUIControls(this);
}

ControllableByMIDIUI::ControllableByMIDIUI() {
  controller = NULL;
}

ControllableByMIDIUI::~ControllableByMIDIUI() {
  if(controller != NULL){
  	controller->unassignUIControls();
  }
  //std::cout << "deleting ControllableByMIDIUI" << endl;
}
