.TH yoshimi 1 " 2021" "yoshimi 2.0.2"
.SH NAME
yoshimi \- a software music synthesiser
.SH SYNOPSIS
\fByoshimi\fP [\fI\-option\fP] [\fIcmd\fP]
.SH DESCRIPTION
\fBYoshimi\fP is a polyphonic multi-part sound synthesiser utilising three distinct 'engines' that can be used separately or together. These can also be stacked into 'kits', typically for percussion. It fully supports both JACK and ALSA for MIDI input and audio output.
.PP
\fBYoshimi\fP can be run in a graphical interface, a command line interface, or with control from both. A number of controls can also be accessed via MIDI. The CLI has its own Readline parser and built-in help system accessed by entering the commands '?' or 'help'.
.PP
The CLI help system is context sensitive, and apart from reminders of common essential commands, only shows the relevant commands. However, it is possible to specifically call for help from other contexts.
.PP
e.g. Within the 'part' context '? config' will show the commands for configuration settings.
.PP
\fBYoshimi\fP has a very extensive MIDI learn capability, exposing the majority of controls. The same MIDI CC and Channel pair can be linked to multiple independent controls. There is also considerable post-learn editing capability.
.PP
Other recent extensions are the ability to import and export entire instrument banks in a safe and obvious manner. It is now also possible to swap any instrument or bank with any other, in any bank root without disrupting the rest of the structure.
.PP
One of the latest additions is the ability to load a list of MIDI-learned settings from the command line at startup.
.PP
The most recent improvements are key and channel aftertouch, fully resizeabe windows, MIDI sync for LFOs and Panning extensions.
.SH COMMANDS
.TP
.BR \-? ", " \-\-help " Shows command syntax."
.TP
.BR \-a ", " \-\-alsa-midi[=<device>] " Use ALSA MIDI input."
.TP
.BR \-A ", " \-\-alsa-audio[=<device>] " Use ALSA audio output."
.TP
.BR \-b ", " \-\-buffersize=<size> " Set the internal buffer size."
.TP
.BR \-c ", " \-\-no-cmdline " Disable command line interface."
.TP
.BR \-C ", " \-\-cmdline " Enable command line interface."
.TP
.BR \-D ", " \-\-define-root " Define path to new bank root dir."
.TP
.BR \-i ", " \-\-no-gui " Disable graphical interface."
.TP
.BR \-I ", " \-\-gui " Enable graphical interface."
.TP
Attempting 'c' and 'i' will produce a warning, and although it is possible to run with both disabled (accepting only MIDI) it is not recommended.
.TP
.BR \-j ", " \-\-jack-midi[=<device>] " Use JACK MIDI input."
.TP
.BR \-J ", " \-\-jack-audio[=<device>] " Connect to JACK server."
.TP
.BR \-k ", " \-\-autostart-jack " Auto start JACK server."
.TP
.BR \-K ", " \-\-auto-connect " Auto connect to jack server."
.TP
.BR \-l ", " \-\-load=<file> " Load .xmz patch set."
.TP
.BR \-L ", " \-\-load-instrument=<file> " Load .xiz instrument file."
.TP
.BR \-M ", " \-\-load-midilearn=<file> " Load .xly learned list file."
.TP
.BR \-N ", " \-\-name-tag=<tag> " Add a tag to the client name."
.TP
.BR \-o ", " \-\-oscilsize=<size> " Set the AddSynth oscillater size."
.TP
.BR \-R ", " \-\-samplerate=<rate> " Set the ALSA audio sample rate."
.TP
.BR \-S ", " \-\-state[=<file>] "  Load previously saved state."
Defaults to "HOME/.config/yoshimi/yoshimi.state"
.TP
.BR \-u ", " \-\-jack-session-file=<file> " Load named JACK session file."
.TP
.BR \-U ", " \-\-jack-session-uuid=<uuid> " Use JACK session uuid."
.TP
Regardless of their position on the command line file loads will always be in the order: session (or state), patch set, instrument, midi-learn
.TP
.BR \-V ", " \-\-version " Print Yoshimi version."
.TP
"Mandatory or optional arguments for long options are also mandatory or optional for any corresponding short options."

\"nroff -man yoshimi.1 | less
